@startuml
skinparam componentStyle rectangle
skinparam defaultTextAlignment center
skinparam linetype ortho

frame "Utenti" as fut {
  [Utente]
  [Creator]
  [GestoreUtenti]
  [RichiestaUpgrade]
  [GestoreRichiesteUpgrade]
}

frame "Pubblicazioni" as fpu {
  [Opera]
  [Post]
  [Evento]
  [Creazione]
  [GestorePost]
  [GestoreEventi]
  [GestoreOpere]
  [GestoreFeed]
}

frame "Interazioni" as fin {
  [Commento]
  [GestoreInterazioni]
  [RichiestaCollaborazione]
  [GestoreCollaborazioni]
}

[GestoreInterazioni] -[hidden]up- [Commento]

frame "Pagamenti" as fpa {
  [Biglietto]
  [Donazione]
  [Ordine]
  [GestorePagamenti]
}

database "DB\nUtenti" as dbut
database "DB\nPubblicazioni" as dbpu
database "DB\nInterazioni" as dbin
database "DB\nPagamenti" as dbpa

rectangle "MessageBroker\t\t\t\t\t\t\t\n\n\n\n" as mb1
rectangle "MessageBroker\t\t\t\t\t\t\t\n\n\n\n" as mb2

fin -[hidden]down- mb1
mb1 -[hidden]left- fut

fut -down- fpa

fut -up- dbut
fpu -right- dbpu
fin -left- dbin
fpa -left- dbpa

mb1 ---up- [GestoreInterazioni] : interazione
mb1 ---down- [Opera] : interazione
mb1 ---down- [Post] : interazione
mb1 ---down- [Evento] : interazione
mb1 ---down- [GestoreFeed] : pubblicazione
mb1 -right- [Utente] : pubblicazione/\ncollaborazione

mb2 -right- [GestorePagamenti] : donazione
mb2 -right- [Utente] : donazione

[GestorePagamenti] .. [Utente]
[GestorePagamenti] .. [Opera]
[GestorePagamenti] .. [Evento]

[GestoreCollaborazioni] -- mb1 : collaborazione

[GestoreOpere] -- mb1 : pubblicazione
[GestoreEventi] -- mb1 : pubblicazione
[GestorePost] -- mb1 : pubblicazione
@enduml