@startuml
skinparam componentStyle rectangle
skinparam defaultTextAlignment center
skinparam linetype ortho

frame "Utenti" as fut {
  [Utente]
  [Creator]
  [GestoreUtenti]
  [RichiestaUpgrade]
  [GestoreRichiesteUpgrade]
}

frame "Pubblicazioni" as fpu {
  [Opera]
  [Post]
  [Evento]
  [Creazione]
  [GestorePost]
  [GestoreEventi]
  [GestoreOpere]
  [GestoreFeed]
}

[Opera] -[hidden]left- [Creazione]

frame "Interazioni" as fin {
  [Commento]
  [GestoreInterazioni]
  [RichiestaCollaborazione]
  [GestoreCollaborazioni]
}

[GestoreInterazioni] -[hidden]up- [Commento]

frame "Pagamenti" as fpa {
  [Donazione]
  [Ordine]
  [GestorePagamenti]
}

[Donazione] -[hidden]up- [Ordine]

database "DB\nUtenti" as dbut
database "DB\nPubblicazioni" as dbpu
database "DB\nInterazioni" as dbin
database "DB\nPagamenti" as dbpa

rectangle "\nMessageBroker\n\t\t\t\t\t\t\t" as mb1
rectangle "MessageBroker" as mb2

fin -[hidden]down- mb1
mb1 -[hidden]left- fut
fpa -[hidden]up- fpu
fut -[hidden]down- fpa

fut -up- dbut
fpu -down- dbpu
fin -left- dbin
fpa --down- dbpa

mb1 -up- [GestoreInterazioni] : interazione
mb1 --down- [Opera] : interazione
mb1 --down- [Post] : interazione
mb1 --down- [Evento] : interazione
mb1 --down- [GestoreFeed] : pubblicazione
mb1 -right- [Utente] : pubblicazione/\ncollaborazione

mb2 --down- [GestorePagamenti] : donazione
mb2 -up- [Utente] : donazione

[GestorePagamenti] .up. [Utente]
[GestorePagamenti] .down. [Opera]
[GestorePagamenti] .down. [Evento]

[GestoreCollaborazioni] -down- mb1 : collaborazione

[GestoreOpere]  ---up- mb1 : pubblicazione
[GestoreEventi] ---up- mb1 : pubblicazione
[GestorePost]   ---up- mb1 : pubblicazione
@enduml