@startuml
'skinparam linetype ortho

class Utente {
+ Id
+ Username
+ Nickname
+ E-mail
+ Password
+ Ruolo
+ ListaFans: Utente[]
+ ListaInspirers: Utente[]
+ IdCreator
}

class Creator {
+ Id
+ Nome
+ Cognome
+ Avatar
+ DataNascita
+ Biografia
+ NumeroFans
+ NumeroInspirers
+ TipologiaArtista
+ EmailPagamento
}

class Creazione {
+ IdCreator
+ IdPubblicazione
+ Tipologia [proprietario, collaboratore]
+ Simbolo [feat.,  ‘x’]
}

class Opera {
+ Nome
+ Lista Immagini
+ Tipologia
+ DataCreazione
+ Dimensioni
+ Descrizione
+ Acquistabile
+ Prezzo
+ Tecnica
+ Informazioni tecniche
+ EmailPagamento
+ Quantità
}

class Post {
+ Titolo
+ Testo
}

class Evento {
+ Nome
+ Descrizione
+ Immagine
+ Luogo [Nome]
+ Coordinate
+ DataOraInizio
+ DataOraFine [?]
+ BookingURL
}

class Commento {
+ Id
+ IdUtente
+ Messaggio
}

class Pubblicazione {
+ Id
+ IdCommenti: Lista
+ Timestamp
}

class Likeable {
+ ListaLike: IdUtente[]
}

class GestoreInterazioni {
+ Aggiungere_like()
+ Rimuovere_like()
+ Aggiungere_commento()
+ Rimuovere_commento()
+ Aggiungere_follow()
+ Rimuovere_follow()
}

class RichiestaCollaborazione {
+ Id
+ IdMittente
+ IdDestinatario [?]
+ Titolo
+ Descrizione
+ Timestamp
+ Contatto
+ Categoria [?]
}

class GestoreCollaborazioni {
+ Richiesta_collaborazione()
+ Richiesta_collaborazione_broadcast()
+ Lista_richieste_broadcast()
}

class GestorePubblicazioni {
+ Elimina_pubblicazione()
}

class GestorePost {
+ Crea_post()
+ Modifica_post()
}

class GestoreOpere {
+ Crea_pera()
+ Modifica_opera()
}

class GestoreEventi {
+ Crea_evento()
+ Modifica_evento()
}

class Donazione {
+ Id
+ IdUtenteMittente
+ IdUtenteCreator
+ Importo
+ Messaggio
+ Timestamp
}

class Ordine {
+ Id
+ IdOpera
+ IdUtente
+ Importo
+ IndirizzoDestinazione
+ Timestamp
}

class GestorePagamenti {
+ Acquista_opera()
+ Invia_donazione()
}

class GestoreFeed {
+ Lista_feed()
}

class RichiestaUpgrade {
+ Id
+ IdUtente
+ Nome
+ Cognome
+ Biografia
+ Piccolo portfolio [file]
+ Testo di motivazione
+ Nome d’arte
+ DataNascita
+ Username
+ Avatar
+ Status
}

class GestoreRichiesteUpgrade {
+ Richiesta_upgrade()
+ Accetta_upgrade()
+ Rifiuta_upgrade()
}

 class GestoreUtenti {
+ Registrazione()
+ Login()
+ Registrazione_Google()
+ Registrazione_Facebook()
+ Cancella_account()
}

Opera -up-> Pubblicazione
Post -up-> Pubblicazione
Evento -up-> Pubblicazione
Pubblicazione -up-> Likeable
Commento -up-> Likeable
GestorePost -up-> GestorePubblicazioni
GestoreOpere -up-> GestorePubblicazioni
GestoreEventi -up-> GestorePubblicazioni

GestoreInterazioni "0..*" -- "1..1" Pubblicazione
GestoreInterazioni "0..*" -- "1..1" Likeable
GestoreInterazioni "0..*" -- "0..1" Utente
GestorePost "0..*" -- "0..1" Utente
GestorePost "0..*" -- "1..1" Post
GestoreOpere "0..*" -- "0..1" Utente
GestoreOpere "0..*" -- "1..1" Opera
GestoreEventi "0..*" -- "0..1" Utente
GestoreEventi "0..*" -- "1..1" Evento
GestorePagamenti "0..*" -- "0..1" Utente
GestorePagamenti "0..*" -- "1..1" Donazione
GestorePagamenti "0..*" -- "1..1" Ordine
GestoreFeed "0..*" -- "1..1" Utente
GestoreFeed "0..*" -- "0..1" Pubblicazione
GestoreRichiesteUpgrade "0..*" -- "0..1" Utente
GestoreRichiesteUpgrade "0..*" -- "1..1" RichiestaUpgrade
GestoreRichiesteUpgrade "0..*" -- "1..1" Creator
GestoreUtenti "0..*" -- "1..1" Utente
GestoreCollaborazioni "0..*" -- "1..1" RichiestaCollaborazione
GestoreCollaborazioni "0..*" -- "0..1" Utente
@enduml