@startuml
skinparam ranksep 80

class Utente {
+ Username
+ Nickname
+ E-mail
+ Password
+ Ruolo \t\t\t\t\t\t\t\t\t\t\t\t\t\t
}

class Creator {
+ Nome
+ Cognome
+ Avatar
+ DataNascita
+ Biografia
+ NumeroFans
+ NumeroInspirers
+ TipologiaArtista
}

class Creazione {
+ Tipologia
+ Simbolo
}

class Opera {
+ Nome
+ Lista Immagini
+ Tipologia
+ DataCreazione
+ Dimensioni
+ Descrizione
+ Acquistabile
+ Prezzo
+ Tecnica
+ Informazioni tecniche
+ Quantità
}

class Post {
+ Titolo
+ Testo
}

class Evento {
+ Nome
+ Descrizione
+ Immagine
+ Luogo
+ Coordinate
+ DataOraInizio
+ DataOraFine [?]
+ BookingURL
}

class Commento {
+ Messaggio
}

class Pubblicazione {
+ Timestamp \t\t\t\t\t\t
}

class Likeable {
}

class RichiestaCollaborazione {
+ Titolo
+ Descrizione
+ Timestamp
+ Contatto
+ Categoria [?]
}

class Biglietto {
+ CodiceIdentificativo
+ Importo
+ Timestamp
+ Posto [?]
}

class Donazione {
+ CodiceIdentificativo
+ Importo
+ Messaggio
+ Timestamp
}

class Ordine {
+ CodiceIdentificativo
+ Importo
+ IndirizzoDestinazione
+ Timestamp
}

class RichiestaUpgrade {
+ Nome
+ Cognome
+ Biografia
+ Piccolo portfolio
+ Testo di motivazione
+ Nome d’arte
+ DataNascita
+ Username
+ Avatar
+ Status
}

Opera --up|> Pubblicazione
Post -up-|> Pubblicazione
Evento -up-|> Pubblicazione
Pubblicazione -up-|> Likeable
Commento -up-|> Likeable
Utente "0..*" o- "1..1" Utente : inspirer\t
Utente "0..*" o- "1..1" Utente : follower
Utente "0..1" *-left- "1..1" Creator : > è un\t
Creazione "1..1" o-down- "0..*" Utente : < crea
Pubblicazione "1..*" *-down- "1..1" Creazione : < di
Commento "1..1" o-down- "0..*" Utente : < autore di
Likeable "0..*" o- "0..*" Utente
Pubblicazione "0..*" *-right- "1..1" Commento : < su\t
Biglietto "1..1" o-up- "0..*" Evento : per >
Biglietto "1..1" o-down- "0..*" Utente : < prenota
Donazione "1..1" o-up- "0..*" Utente : mittente di <
Donazione "1..1" o-up- "0..*" Utente : destinatario di <
Ordine "1..1" o--down- "0..*" Utente : < ordina
Ordine "1..1" o-up- "0..*" Opera : riguarda >
RichiestaUpgrade "1..1" o-up- "0..*" Utente : < richiede
RichiestaCollaborazione "1..1" o-up- "0..*" Utente : mittente di <
RichiestaCollaborazione "0..1" o-up- "0..*" Utente : destinatario di <

Post -[hidden]left- Evento
Opera -[hidden]right- Evento
Biglietto -[hidden]right- Creazione
@enduml