@startuml
'skinparam linetype ortho

class Utente {
+ Username
+ Nickname
+ E-mail
+ Password
+ Ruolo
\t\t\t\t\t\t\t\t
}

class Creator {
+ Nome
+ Cognome
+ Avatar
+ DataNascita
+ Biografia
+ NumeroFans
+ NumeroInspirers
+ TipologiaArtista
}

class Creazione {
+ Tipologia
+ Simbolo
}

class Opera {
+ Nome
+ Lista Immagini
+ Tipologia
+ DataCreazione
+ Dimensioni
+ Descrizione
+ Acquistabile
+ Prezzo
+ Tecnica
+ Informazioni tecniche
+ Quantità
}

class Post {
+ Titolo
+ Testo
}

class Evento {
+ Nome
+ Descrizione
+ Immagine
+ Luogo
+ Coordinate
+ DataOraInizio
+ DataOraFine [?]
+ BookingURL
}

class Commento {
+ Messaggio
}

class Pubblicazione {
+ Timestamp
}

class Likeable {
}

class RichiestaCollaborazione {
+ Titolo
+ Descrizione
+ Timestamp
+ Contatto
+ Categoria [?]
}

class Biglietto {
+ CodiceIdentificativo
+ Importo
+ Timestamp
+ Posto [?]
}

class Donazione {
+ CodiceIdentificativo
+ Importo
+ Messaggio
+ Timestamp
}

class Ordine {
+ CodiceIdentificativo
+ Importo
+ IndirizzoDestinazione
+ Timestamp
}

class RichiestaUpgrade {
+ Nome
+ Cognome
+ Biografia
+ Piccolo portfolio
+ Testo di motivazione
+ Nome d’arte
+ DataNascita
+ Username
+ Avatar
+ Status
}

Utente "0..*" o- "1..1" Utente : inspirer\\t
Utente "0..*" o- "1..1" Utente : follower
Utente "0..1" *-- "1..1" Creator
Creazione "1..1" o-- "0..*" Utente
Pubblicazione "1..*" *- "1..1" Creazione
Commento "1..1" o-- "0..*" Utente
Opera -up|> Pubblicazione
Post -up-|> Pubblicazione
Evento -up-|> Pubblicazione
Pubblicazione -up-|> Likeable
Commento -up-|> Likeable
Likeable "0..*" o-- "0..*" Utente
Pubblicazione "0..*" *-right- "1..1" Commento : ha\t >
Biglietto "1..1" o-up- "0..*" Evento
Biglietto "1..1" o-down- "0..*" Utente
Donazione "2..2" o-up- "0..*" Utente
Ordine "1..1" o-right- "0..*" Utente : \t\t
Ordine "1..1" o--up- "0..*" Opera
RichiestaUpgrade "1..1" o-up- "0..*" Utente : \t\t
RichiestaCollaborazione "1..1" o-up- "0..*" Utente : mittente
RichiestaCollaborazione "0..1" o-up- "0..*" Utente : destinatario

Opera -[hidden]right- Evento
Biglietto -[hidden]right- Creazione
@enduml