name: Deploy project

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/microservice-users
          path: 'microservice-users'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/microservice-publications
          path: 'microservice-publications'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/microservice-payments
          path: 'microservice-payments'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/microservice-interactions
          path: 'microservice-interactions'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/api-gateway
          path: 'api-gateway'
          token: ${{ secrets.GH_PAT }}
      - run: |
          curl https://get.okteto.com -sSfL | sh
          okteto login --token ${{ secrets.OKTETO_TOKEN }}
          okteto namespace taass-acontenti
          okteto kubeconfig
      - run: |
          export GATEWAY_URL=https://api-gateway-taass-acontenti.cloud.okteto.net
          for f in ./**/orchestration/*.yaml; do cat $f | envsubst | kubectl apply -f -; done
  
