name: Deploy project

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      namespace:
        type: choice
        options:
          - taass-acontenti
          - taass-zathsl
          - taass-alessiofamiani
        required: true
        description: Okteto namespace
      loadSampleData:
        type: boolean
        required: true
        default: true
        description: Load sample data

jobs:
  deploy:
    name: Deploy on Okteto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/microservice-users
          path: 'microservice-users'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/microservice-publications
          path: 'microservice-publications'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/microservice-payments
          path: 'microservice-payments'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/microservice-interactions
          path: 'microservice-interactions'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/api-gateway
          path: 'api-gateway'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/front-end
          path: 'front-end'
          token: ${{ secrets.GH_PAT }}
      - run: |
          curl https://get.okteto.com -sSfL | sh
          okteto login --token ${{ secrets.OKTETO_TOKEN }}
          okteto namespace ${{ github.event.inputs.namespace }}
          okteto kubeconfig
      - run: kubectl delete all --all
      - run: for f in ./**/orchestration/*.yaml; do cat $f | envsubst | kubectl apply -f -; done
        env:
          GATEWAY_URL: ${{ format('https://api-gateway-{0}.cloud.okteto.net', github.event.inputs.namespace) }}
  load-sample-data:
    name: Load sample data
    if: ${{ github.event.inputs.loadSampleData == true }}
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/sample-data-bot
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: python -m pip install --upgrade pipenv wheel
      - run: pipenv install --deploy --dev
      - run: sleep 120s
      - run: pipenv run python main.py --api-url ${{ format('https://api-gateway-{0}.cloud.okteto.net', github.event.inputs.namespace) }}
