name: Deploy project

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      gatewayURL:
        type: choice
        options:
          - https://api-gateway-taass-acontenti.cloud.okteto.net
          - https://api-gateway-taass-zathsl.cloud.okteto.net
          - https://api-gateway-taass-alessiofamiani.cloud.okteto.net
        required: true
        description: API Gateway URL
        

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/microservice-users
          path: 'microservice-users'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/microservice-publications
          path: 'microservice-publications'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/microservice-payments
          path: 'microservice-payments'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/microservice-interactions
          path: 'microservice-interactions'
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: creative-hub-taass/api-gateway
          path: 'api-gateway'
          token: ${{ secrets.GH_PAT }}
      - run: |
          curl https://get.okteto.com -sSfL | sh
          okteto login --token ${{ secrets.OKTETO_TOKEN }}
          okteto namespace taass-acontenti
          okteto kubeconfig
      - run: for f in ./**/orchestration/*.yaml; do cat $f | envsubst | kubectl apply -f -; done
        env:
          GATEWAY_URL: ${{ github.event.inputs.gatewayURL }}
